### PR TITLE
fix: Adds Google Ruby style. Fixes #25.

### LINKED ISSUE #25: Use Google Ruby Sample Style
FYI, there's a new Google Ruby Style Guide:
https://github.com/googleapis/ruby-style

We should inherit from that base style.

### PR DESCRIPTION
**Pull request by grant**
Extends [Google's new Ruby Style lint rules](https://github.com/googleapis/ruby-style).

There currently are a handful of offenses:

```
rubocop
Inspecting 42 files
.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

Offenses:
42 files inspected, 606 offenses detected
```

Uses `--fix` to fix a few of them.

### CODE REVIEW

**Comment by erickoledadevrel** [comment]
Deferring to @sqrrrl, since he knows Ruby much better than I do and is managing the team's GitHub presence.

File: slides/snippets/lib/file_snippets.rb [hunk 1]
```diff
@@ -86,43 +86,44 @@ def create_textbox_with_text(presentation_id, page_id)
...
 
-    # Insert text into the box, using the supplied element ID.
-    {
-      insert_text: {
-        object_id_prop: element_id,
-        insertion_index: 0,
-        text: 'New Box Text Inserted!'
-      }
-    }]
+                # Insert text into the box, using the supplied element ID.
```
Comment (sqrrrl) [inline slides/snippets/lib/file_snippets.rb]: Indenting seems way off here.

Comment (grant) [reply slides/snippets/lib/file_snippets.rb]: This is because the opening `{` is on column 17.
If we'd like to change this, we need to change the column of the open curly brace, perhaps moving it to he next line.

Comment (sqrrrl) [reply slides/snippets/lib/file_snippets.rb]: yeah, see if you can get it to line up better. The two requests in the array should be aligned.

**Comment by sqrrrl** [comment]
Oh, and just noticed the comment in the PR about 'purposefully breaks the Travis build.' Don't do that. If you have a plan for a fast follow fix, please let me know. Otherwise I won't merge until things are good again.

The current build failure isn't even the rule violations -- it's an error finding the google-style gem.

**Comment by grant** [comment]
Right.
Fixed the build failure and updated the PR comment.
